### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by cracker0dks** [dragosch/kurento-group-call#1]
Hey, 
nice work dude! My Problem is, that I dont get your example running.
Not in the current version and also not on the init commit.
Did you got this projekt running at any point ?

What I have done: 
- fixed syntax errors in example/server.js 
- fixed the example/server.js for new express version (without middleware)
- checked out your old versions 

But at any point I get errors. The problem with the current version is (i think), that you changed from ws to socket.io but only on server.

Note: the link in your readme to java doc is not working anymore.

Can you help me with that ?
Thanks for your work!

**Comment by dragosch** [comment]
hey,
thanks for the feedback,
You are right the example is not running at the moment. I will fix it asap !
